title: "suggitpe"
description: "Notes, projects, and passing curiosities."
url: "https://suggitpe.github.io"
author: "suggitpe"

# Use the official Midnight theme via remote_theme
theme: "Minima"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections for Presentations & Recipes
collections:
  presentations:
    output: true
    permalink: /presentations/:name/
  recipes:
    output: true
    permalink: /recipes/:name/

# Keep your blog permalink style
permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _site
