title: Pete Suggitt

url: http://suggs.org.uk
blogimages: {{ site.url }}/blog-images

ghe: https://github.com/suggitpe

#highlighter: rouge
#markdown: kramdown
#kramdown:
#    input: GFM
#    toc_levels: 1..3

# gems:
  # - jekyll-sitemap
