title: "suggitpe"
description: "Notes, projects, and passing curiosities."
url: "https://suggitpe.github.io"
author: "suggitpe"

remote_theme: poole/hyde

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

collections:
  presentations:
    output: true
    permalink: /presentations/:name/
  recipes:
    output: true
    permalink: /recipes/:name/

permalink: /blog/:year/:month/:day/:title/
