title: "suggitpe"
description: "Notes, projects, and passing curiosities."
url: "https://suggitpe.github.io"
baseurl: ""                 # empty for user/organization sites

remote_theme: fongandrew/hydeout

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Helps GitHub metadata links in the sidebar
repository: suggitpe/suggitpe.github.io

# Your sections
collections:
  presentations:
    output: true
    permalink: /presentations/:name/
  recipes:
    output: true
    permalink: /recipes/:name/

permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
