title: "suggitpe"
description: "Notes, projects, and passing curiosities."
url: "https://suggitpe.github.io"
author: "suggitpe"

# Use Hyde directly from GitHub with the remote theme mechanism
remote_theme: poole/hyde

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Your existing collections & permalinks can stay
collections:
  presentations:
    output: true
    permalink: /presentations/:name/
  recipes:
    output: true
    permalink: /recipes/:name/
permalink: /blog/:year/:month/:day/:title/
